config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'pages', to: "pages#index", as: :pages
    get 'documents/:id', to: "documents#index", as: :documents
    get 'users/:id', to: "users#show", as: :show_user
    get 'users/:id/edit', to: "users#edit", as: :edit_user
    put 'users/:id/update', to: "users#update", as: :update_user
    delete 'user/:id', to: "users#destroy", as: :user_delete
    delete 'page/:id', to: "pages#destroy", as: :page_delete
    get 'decline_request', to: "users#decline_request", as: :decline_request
    put 'decline_request/:id', to: "users#update_request_status", as: :update_request_status
    delete 'decline_request/:id', to: "users#destroy_request", as: :decline_request_delete
  end

  authenticated :admin do
    root :to => "admins/users#index"
  end

  authenticated :user do
    root :to => "dashboard#index"
  end

  devise_for :admins, controllers: { registrations: "admins/registrations",sessions: "admins/sessions", confirmations: "admins/confirmations", passwords: "admins/passwords", unlocks: "admins/unlocks" }
  get 'subscription',to: 'subscriptions#idnex'
  post 'subscriptions', to: 'subscriptions#create'
  get 'authenticates/index'

  devise_for :users, controllers: { registrations: "registrations" }
  post 'check_email', to: 'users#check_email'
  post 'check_page', to: 'users#check_page'
  post 'is_email_exist', to: 'users#is_email_exist'
  get 'staticpage/index'
  get 'staticpage/test'

  get 'staticpage/dropbox'
  get 'staticpage/googledrive'
  get 'staticpage/onedrive'
  get 'staticpage/googleapidrive'

  root to: "dashboard#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/:id/edit', to: 'users#edit', as: :edit_user
  put 'users/:id', to: 'users#update', as: :update_user
  get 'dashboard/privacy_policy', to: 'dashboard#privacy_policy', as: :privacy_policy
  get 'dashboard/switch_plan', to: 'dashboard#switch_plan', as: :switch_plan
  get 'dashboard/addcard/:plan_id', to: 'dashboard#addcard', as: :addcard
  post 'subscription_checkout', to: 'dashboard#subscription_checkout', as: :subscription_checkout
  post 'payment_decline_request', to: 'dashboard#payment_decline_request', as: :payment_decline_request

  resources :pages do
  	collection do
  		post 'upload'
      get ':type', to: 'pages#new_page',as: :new_page
      post 'page_exist', to: 'pages#page_exist', as: :page_exist
      put 'pages/:id', to: 'pages#update'
  	end
  end
  post 'add_question_setting/:id', to: 'pages#add_question', as: :add_question
  get 'remove_question/:id', to: 'pages#remove_question', as: :remove_question
  post 'add_question_answer', to: 'pages#add_question_answer', as: :add_question_answer
  get ':id', to: 'pages#show_page',as: :show_page
  get ':id/dropbox_download' => 'pages#dropbox_download', as: 'dropbox_download'
  delete ':id/remove_from_dropbox' => 'pages#remove_from_dropbox', as: :remove_from_dropbox
  get ':id/googledrive_download', to: 'pages#googledrive_download', as: :googledrive_download
  delete ':id/remove_from_googledrive' => 'pages#remove_from_googledrive', as: :remove_from_googledrive
  get ':id/onedrive_download', to: 'pages#onedrive_download', as: :onedrive_download
  delete ':id/remove_from_onedrive' => 'pages#remove_from_onedrive', as: :remove_from_onedrive


  match "*path" => redirect("/") , via: [:get, :post]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :dropbox_detail, :dependent => :destroy
  has_one :google_detail, :dependent => :destroy
  has_one :onedrive_detail, :dependent => :destroy
  has_many :pages, :dependent => :destroy
  has_many :user_subscriptions, :dependent => :delete_all
  has_many :payment_decline_requests, :dependent => :delete_all
  has_one :user_uploaded_file_size_total, dependent: :destroy

  after_create :create_user_uploaded_file_size_total

  def create_user_uploaded_file_size_total
    @user_uploaded_file_size_total = UserUploadedFileSizeTotal.new(user_id: self.id, start_date: self.created_at, end_date: self.created_at + 7.days, total_size: 0.0 )
    @user_uploaded_file_size_total.save
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  layout "admins"

  def index
    @users = User.all.includes(:pages)
  end

  def show
    @user = User.find(params[:id])
    @user_sub = @user.user_subscriptions.includes(:subscription_plan)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User was updated."
      redirect_to root_path
    else
      flash[:error] = "User was not updated."
      redirect_to root_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted successfully."
    redirect_to root_path
  end

  def decline_request
    @decline_request = PaymentDeclineRequest.all.includes(:user,:subscription_plan)
  end

  def update_request_status
    @decline_request = PaymentDeclineRequest.find(params[:id])
    if @decline_request.update(is_approved: true)
      flash[:notice] = "Request was approved successfully."
      redirect_to admins_decline_request_path
    else
      flash[:error] = "Request was not approve successfully."
      redirect_to admins_decline_request_path
    end
  end

  def destroy_request
    @decline_request = PaymentDeclineRequest.find(params[:id])
    @decline_request.destroy
    flash[:notice] = "Request deleted successfully."
    redirect_to admins_decline_request_path
  end

  private

	def user_params
		params.require(:user).permit(:email)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(email: params[:email])
  	redirect_to edit_user_path(@user)
  end

  def check_email
    @user = User.find_by_email(params[:user][:email])
    respond_to do |format|
      format.json { render :json => {:valid => !@user} }
    end
  end

  def is_email_exist
    @user = User.find_by_email(params[:user][:email])
    @user_res = @user.present? ? true : false
    respond_to do |format|
      format.json { render :json => {:valid => @user_res} }
    end
  end

  def check_page
    @page = Page.find_by_name(params[:user][:pagename])
    respond_to do |format|
      format.json { render :json => {:valid => !@page} }
    end
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/decline_request.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Users </h1>
</section>

<!-- Main content -->
<section class="content">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-lg-12 col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Manage user's payment decline request </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="users" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
            <tr>
              <th>Email</th>
              <th>Plan</th>
              <th>Comment</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
              <% @decline_request.each do |d_r| %>
                <tr>
                  <td><%= d_r.user.email %></td>
                  <td>
                    <%= d_r.subscription_plan.name %>
                  </td>
                  <td><%= d_r.comment %></td>
                  <td>
                    <% if d_r.is_approved %>
                      Approved
                    <% else %>
                      <%= link_to "Approve",admins_update_request_status_path(d_r.id), method: :put, data: { confirm: "Are you sure you want to approve this request?" },class: 'btn btn-primary' %>
                    <% end %>
                  </td>
                  <td class="action">
                    <%= link_to admins_decline_request_delete_path(d_r.id), method: :delete, data: { confirm: "Are you sure you want to delete this request?" } do %>
                      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
  </div>
</section>


<script>
  var users_table;
  users_table = null;

  document.addEventListener("turbolinks:load", function() {
    return users_table = $('#users').DataTable({
      retrieve: true,
      columnDefs: [
         { orderable: false, targets: -1 }
      ]
    });
  });

  document.addEventListener("turbolinks:before-cache", function() {
    if ($('#users_wrapper').length === 1) {
      return users_table.destroy();
    }
  });
</script>

app/views/admins/users/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Edit user details </h1>
</section>

<!-- Main content -->
<section class="content">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-lg-12 col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Change User Personal </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <%= form_for(@user, url: admins_update_user_path(@user), html: { method: :put }) do |f| %>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <div class="form-group">
                  <label>Email</label>
                  <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true   %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-8">
              </div>
              <!-- /.col -->
              <div class="col-xs-4">
                <%= f.submit "Update",class: "btn btn-primary btn-block btn-flat" %>
              </div>
              <!-- /.col -->
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/admins/users/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Users </h1>
</section>

<!-- Main content -->
<section class="content">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-lg-12 col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Manage User </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="users" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
            <tr>
              <th>Email</th>
              <th>Number of pages</th>
              <th>Register at</th>
              <th>Last sign in</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.email %></td>
                  <td>
                    <%= link_to user.pages.size, admins_pages_path(id: user.id) %>
                  </td>
                  <td><%= user.created_at.in_time_zone("Chennai").strftime("%d %B %Y") %></td>
                  <td><%= user.last_sign_in_at.in_time_zone("Chennai").strftime("%d-%m-%Y") %></td>
                  <td class="action">
                    <%= link_to admins_show_user_path(user.id) do %>
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    <% end %>
                    <%#= link_to admins_edit_user_path(user.id) do %>
  										<!-- <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> -->
  									<%# end %>
                    <%= link_to admins_user_delete_path(user.id), method: :delete,data: { confirm: "Are you sure you want to delete this user?" } do %>
                      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
  </div>
</section>


<script>
  var users_table;
  users_table = null;

  document.addEventListener("turbolinks:load", function() {
    return users_table = $('#users').DataTable({
      retrieve: true,
      columnDefs: [
         { orderable: false, targets: -1 }
      ]
    });
  });

  document.addEventListener("turbolinks:before-cache", function() {
    if ($('#users_wrapper').length === 1) {
      return users_table.destroy();
    }
  });
</script>

app/views/admins/users/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>User details </h1>
</section>

<!-- Main content -->
<section class="content">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-lg-12 col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">User Personal Info </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <label class="mr-10">Email: </label><%= @user.email %>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <label class="mr-10">Number of pages: </label><%= @user.pages.size %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <label class="mr-10">Registered at: </label><%= @user.created_at.in_time_zone("Chennai").strftime("%d %B %Y") %>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <label class="mr-10">Last sign in: </label><%= @user.last_sign_in_at.in_time_zone("Chennai").strftime("%d-%m-%Y") %>
            </div>
          </div>
          <% if @user_sub.present? %>
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="mr-10">Current subscription plan: </label><%= @user_sub.last.subscription_plan.name %>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="mr-10">Amount: </label>$<%=  @user_sub.last.subscription_plan.amount %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="mr-10">Subscription mode: </label><%= @user_sub.last.livemode ? 'Live' : 'Test' %>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="mr-10">Subscription plan expire at: </label><%=  @user_sub.last.subscription_end_priod.in_time_zone("Chennai").strftime("%d-%m-%Y %H:%M") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="box">
        <div class="box-header">
          <h3 class="box-title">User subscriptions </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="user_payment" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>Subscription plan</th>
                <th>Subscription mode</th>
                <th>Subscription start at</th>
                <th>Subscription end at</th>
                <th>Amount</th>
                <th>Stripe subscription id</th>
                <th>Stripe customer id</th>
                <th>Stripe invoice id</th>
              </tr>
            </thead>
            <tbody>
              <% @user_sub.each do |u_s| %>
                <tr>
                  <td><%= u_s.subscription_plan.name %></td>
                  <td><%= u_s.livemode ? 'Live' : 'Test' %></td>
                  <td><%= u_s.subscription_start_priod.in_time_zone("Chennai").strftime("%d-%m-%Y %H:%M") %></td>
                  <td><%= u_s.subscription_end_priod.in_time_zone("Chennai").strftime("%d-%m-%Y %H:%M") %></td>
                  <td>$<%= u_s.subscription_plan.amount %></td>
                  <td><%= u_s.stripe_subscription_id %></td>
                  <td><%= u_s.stripe_customer_id %></td>
                  <td><%= u_s.stripe_invoice_id %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  var user_payment_table;
  user_payment_table = null;

  document.addEventListener("turbolinks:load", function() {
    return user_payment_table = $('#user_payment').DataTable();
  });

  document.addEventListener("turbolinks:before-cache", function() {
    if ($('#user_payment_wrapper').length === 1) {
      return user_payment_table.destroy();
    }
  });
</script>