config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'pages', to: "pages#index", as: :pages
    get 'documents/:id', to: "documents#index", as: :documents
    get 'users/:id', to: "users#show", as: :show_user
    get 'users/:id/edit', to: "users#edit", as: :edit_user
    put 'users/:id/update', to: "users#update", as: :update_user
    delete 'user/:id', to: "users#destroy", as: :user_delete
    delete 'page/:id', to: "pages#destroy", as: :page_delete
    get 'decline_request', to: "users#decline_request", as: :decline_request
    put 'decline_request/:id', to: "users#update_request_status", as: :update_request_status
    delete 'decline_request/:id', to: "users#destroy_request", as: :decline_request_delete
  end

  authenticated :admin do
    root :to => "admins/users#index"
  end

  authenticated :user do
    root :to => "dashboard#index"
  end

  devise_for :admins, controllers: { registrations: "admins/registrations",sessions: "admins/sessions", confirmations: "admins/confirmations", passwords: "admins/passwords", unlocks: "admins/unlocks" }
  get 'subscription',to: 'subscriptions#idnex'
  post 'subscriptions', to: 'subscriptions#create'
  get 'authenticates/index'

  devise_for :users, controllers: { registrations: "registrations" }
  post 'check_email', to: 'users#check_email'
  post 'check_page', to: 'users#check_page'
  post 'is_email_exist', to: 'users#is_email_exist'
  get 'staticpage/index'
  get 'staticpage/test'

  get 'staticpage/dropbox'
  get 'staticpage/googledrive'
  get 'staticpage/onedrive'
  get 'staticpage/googleapidrive'

  root to: "dashboard#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/:id/edit', to: 'users#edit', as: :edit_user
  put 'users/:id', to: 'users#update', as: :update_user
  get 'dashboard/privacy_policy', to: 'dashboard#privacy_policy', as: :privacy_policy
  get 'dashboard/switch_plan', to: 'dashboard#switch_plan', as: :switch_plan
  get 'dashboard/addcard/:plan_id', to: 'dashboard#addcard', as: :addcard
  post 'subscription_checkout', to: 'dashboard#subscription_checkout', as: :subscription_checkout
  post 'payment_decline_request', to: 'dashboard#payment_decline_request', as: :payment_decline_request

  resources :pages do
  	collection do
  		post 'upload'
      get ':type', to: 'pages#new_page',as: :new_page
      post 'page_exist', to: 'pages#page_exist', as: :page_exist
      put 'pages/:id', to: 'pages#update'
  	end
  end
  post 'add_question_setting/:id', to: 'pages#add_question', as: :add_question
  get 'remove_question/:id', to: 'pages#remove_question', as: :remove_question
  post 'add_question_answer', to: 'pages#add_question_answer', as: :add_question_answer
  get ':id', to: 'pages#show_page',as: :show_page
  get ':id/dropbox_download' => 'pages#dropbox_download', as: 'dropbox_download'
  delete ':id/remove_from_dropbox' => 'pages#remove_from_dropbox', as: :remove_from_dropbox
  get ':id/googledrive_download', to: 'pages#googledrive_download', as: :googledrive_download
  delete ':id/remove_from_googledrive' => 'pages#remove_from_googledrive', as: :remove_from_googledrive
  get ':id/onedrive_download', to: 'pages#onedrive_download', as: :onedrive_download
  delete ':id/remove_from_onedrive' => 'pages#remove_from_onedrive', as: :remove_from_onedrive


  match "*path" => redirect("/") , via: [:get, :post]
end

app/views/pages/_create_page.html.erb
<div class="form-group">
  <label for="exampleInputEmail1">Choose the URL name that you send to anyone</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">http://cloudtransfr.com/</span>
    <%= f.text_field :name,class:"form-control"%>
  </div>
</div>

<% if user_signed_in? %>
  <%= f.hidden_field :cloud_storage_type, value: "#{current_user.google_detail.present? ? 'googledrive' : current_user.onedrive_detail.present? ? 'onedrive' : current_user.dropbox_detail.present? ? 'dropbox' : ''}" %>
<% end %>

<%= f.submit 'Create',class:"violat-btn" %>

app/views/pages/_question_form.html.erb
<div class="uploadingForm">
  <ul id="<%= ques[:id] %>">
    <li>
      <div class="form-group p_question">
        <%= text_field_tag 'page[question]', nil, class: "form-control", value: ques[:question],onkeyup: "removeError($(this),'p_question')" %>
      </div>
    </li>
    <li>
      <div class="form-group select-table">
        <%= select_tag "page[question_type]", options_for_select(@question_type, ques[:question_type]), class: "form-control" %>
      </div>
    </li>
    <li>
      <div class="form-group p_description">
        <%= text_field_tag 'page[description]', nil, class: "form-control", value: ques[:description],onkeyup: "removeError($(this),'p_description')" %>
      </div>
    </li>
    <li>
      <div class="clear-line">
        <div class="checkbox remember">
          <label>
            <%= check_box_tag 'page[is_required]', ques[:is_required], ques[:is_required] %>
            <span></span> Required
          </label>
        </div>
      </div>
    </li>
    <li class="formButton">
      <div class="newForm">
        <div class="btn-group" role="group" >
          <button type="button" class="btn btn-add-setting" id="addNewQuestion" onclick="appendNewQuestionForm($(this));"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
        </div>
      </div>
      <div class="removeForm">
        <div class="btn-group" role="group" >
          <button type="button" class="btn btn-danger" id="RemoveQuestion" onclick="removeQuestionForm($(this))"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/pages/index.html.erb
<!-- <h1>List of pages</h1> -->

<%#= link_to "New Page", new_page_path %>
<%# @pages.each do |page| %>
<!-- <li><%#= link_to page.name, page_path(page) %></li> -->
<%# end %>
<%#= link_to "New Page", new_page_path %>
<div class="pad-block gray-bg first-pad page-list">
	<div class="container">
		<div class="main-title filter">
			<h2>Your Pages</h2>
			<div class="btn-group" role="group" aria-label="...">
				<button type="button" class="btn btn-default toggle-view active" data-id="lib-grid">
					<span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-default toggle-view" data-id="lib-listing">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
				</button>
			</div>
		</div>
		<% if user_signed_in? && current_user.dropbox_detail.present? %>
			<div class="page-title">
				<h2>Dropbox Page</h2>
				<% if @allow_pages %>
					<%= link_to "New Page", new_page_pages_path('dropbox'), class: "violat-btn pull-right" %>
				<% elsif current_user.user_subscriptions.present? && current_user.user_subscriptions.last.subscription_plan_id == 2 && @plan_two_pages %>
					<%= link_to "New Page", new_page_pages_path('dropbox'), class: "violat-btn pull-right" %>
				<% elsif current_user.user_subscriptions.present? && current_user.user_subscriptions.last.subscription_plan_id == 3  %>
					<%= link_to "New Page", new_page_pages_path('dropbox'), class: "violat-btn pull-right" %>
				<% end %>
			</div>
			<ul class="page-views new-drive lib-grid">
				<% @drop_box_pages.each do |page| %>
				<li class="page-grid">
					<div class="lib-box">
						<%= link_to show_page_path(page),class: "lib-icn", method: :get do %>
							<%= image_tag "dropbox.png"%>
						<% end %>
						<div class="lib-act">
							<h3>
								<% if user_signed_in? && current_user.dropbox_detail.blank? %>
								<%= link_to page.name, staticpage_index_path %>
							<% else %>
								<%= link_to page.name, show_page_path(page), method: :get %>
								<button class='my_clip_button btn btn-primary' data-clipboard-text="https://cloudtransfr-staging.herokuapp.com<%= show_page_path(page) %>" id="google-drive-btn" title='Click me to copy to clipboard.'>Copy</button>
								<% end %>
							</h3>
							<div class="dropdown act-drop">
								<button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
									<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
								</button>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
									<li><%= link_to edit_page_path(:id => page.id), class: "setting-btn", method: :get do %>
										<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
										Settings
										<% end%>
									</li>
									<li>
										<%= link_to page_path(page.id), method: :delete,data: { confirm: "Are you sure you want to delete this page?" } do %>
											<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
											Delete
										<% end %>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</li>
			<% end %>
		</ul>
		<% end %>

		<% if user_signed_in? && current_user.google_detail.present? %>
			<div class="page-title">
				<h2>Google Drive Page</h2>
				<% if @allow_pages %>
					<%= link_to "New Page", new_page_pages_path('googledrive'), class: "violat-btn pull-right" %>
				<% elsif current_user.user_subscriptions.present? && current_user.user_subscriptions.last.subscription_plan_id == 2 && @plan_two_pages %>
					<%= link_to "New Page", new_page_pages_path('googledrive'), class: "violat-btn pull-right" %>
				<% elsif current_user.user_subscriptions.present? && current_user.user_subscriptions.last.subscription_plan_id == 3  %>
					<%= link_to "New Page", new_page_pages_path('googledrive'), class: "violat-btn pull-right" %>
				<% end %>
			</div>
			<ul class="page-views new-drive lib-grid">
				<% @google_drive_pages.each do |page| %>
				<li class="page-grid">
					<div class="lib-box">
						<%= link_to show_page_path(page),class: "lib-icn", method: :get do %>
							<%= image_tag "google-drive.png"%>
						<% end %>
						<!-- <a href="pages-inner.html" class="lib-icn"><img src="../assets/folder.png" alt="" /></a> -->
						<div class="lib-act">
							<h3>
								<% if user_signed_in? && current_user.google_detail.blank? %>
								<%= link_to page.name, staticpage_index_path %>
							<% else %>
								<%= link_to page.name, show_page_path(page) %>
								<button class='my_clip_button btn btn-primary' data-clipboard-text="https://cloudtransfr-staging.herokuapp.com<%= show_page_path(page) %>" id="google-drive-btn" title='Click me to copy to clipboard.'>Copy</button>
								<% end %>
							</h3>
							<div class="dropdown act-drop">
								<button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
									<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
								</button>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
									<li>
										<%= link_to edit_page_path(:id => page.id), class: "setting-btn", method: :get do %>
											<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Settings
										<% end%>
									</li>
									<li>
										<%= link_to page_path(page.id), method: :delete,data: { confirm: "You sure?" } do %>
											<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
											Delete
										<% end %>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</li>
				<% end %>
			</ul>
		<% end %>

		<% if user_signed_in? && current_user.onedrive_detail.present? %>
			<div class="page-title">
				<h2>OneDrive Page</h2>
				<% if @allow_pages %>
					<%= link_to "New Page", new_page_pages_path('onedrive'), class: "violat-btn pull-right" %>
				<% elsif current_user.user_subscriptions.present? && current_user.user_subscriptions.last.subscription_plan_id == 2 && @plan_two_pages %>
					<%= link_to "New Page", new_page_pages_path('onedrive'), class: "violat-btn pull-right" %>
				<% elsif current_user.user_subscriptions.present? && current_user.user_subscriptions.last.subscription_plan_id == 3  %>
					<%= link_to "New Page", new_page_pages_path('onedrive'), class: "violat-btn pull-right" %>
				<% end %>
			</div>
			<ul class="page-views new-drive lib-grid">
				<% @one_drive_pages.each do |page| %>
				<li class="page-grid">
					<div class="lib-box">
						<%= link_to show_page_path(page),class: "lib-icn", method: :get do %>
							<%= image_tag "one-drive.png"%>
						<% end %>
						<div class="lib-act">
							<h3>
								<% if user_signed_in? && current_user.onedrive_detail.blank? %>
								<%= link_to page.name, staticpage_index_path %>
							<% else %>
								<%= link_to page.name, show_page_path(page), method: :get %>
								<button class='my_clip_button btn btn-primary' data-clipboard-text="https://cloudtransfr-staging.herokuapp.com<%= show_page_path(page) %>" id="google-drive-btn" title='Click me to copy to clipboard.'>Copy</button>
								<% end %>
							</h3>
							<div class="dropdown act-drop">
								<button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
									<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
								</button>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
									<li>
										<%= link_to edit_page_path(:id => page.id), class: "setting-btn", method: :get do %>
											<span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Settings
										<% end%>
									</li>
									<li>
										<%= link_to page_path(page.id), method: :delete,data: { confirm: "You sure?" } do %>
											<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
											Delete
										<% end %>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</li>
				<% end %>
			</ul>
		<% end %>

	</div>
</div>

<script>
	$(window).scroll(function () {
		if ($(this).scrollTop() > 1) {
			$('header').addClass("sticky");
			$('body').addClass("sticky-b");
		} else {
			$('header').removeClass("sticky");
			$('body').removeClass("sticky-b");
		}
	});
	$('.toggle-view').click(function () {
		$('.toggle-view').removeClass('active');
		$(this).addClass('active');
		var add_class = $(this).attr('data-id');
		if (add_class == 'lib-grid') {
			$('.page-views').removeClass('lib-listing');
			$('.page-views').addClass(add_class);
		} else {
			$('.page-views').removeClass('lib-grid');
			$('.page-views').addClass(add_class);
		}
	});
</script>
<script>
	$(document).ready(function() {
    var clip = new ZeroClipboard($(".my_clip_button"))
  });
</script>

app/views/pages/new_page.html.erb
<div class="pad-block gray-bg first-pad page-list">
  <div class="container">
    <div class="main-title">
      <h2>Please create the url </h2>
    </div>
    <div class="setting-wrap">
      <%= form_for @pages do |f| %>
        <% if @pages.errors.any? %>
        <div>
          <h2><%= pluralize(@pages.errors.count, "error") %>prohibited this pages from being saved:</h2>
          <ul>
            <% @pages.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <% unless params[:type] == 'new' %>
          <%= f.hidden_field :cloud_storage_type,value: params[:type] %>
          <div class="form-group">
            <label for="exampleInputEmail1">Choose the URL name that you send to anyone</label>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon3">http://cloudtransfr.com/</span>
              <%= f.text_field :name,class:"form-control"%>
            </div>
          </div>
          <div class="btn-wrap">
            <div class="text-center">
              <!-- <button type="button" class="red-btn">Cancel</button> -->
              <%= f.submit 'Create',class:"violat-btn" %>
            </div>
          </div>
        <% else %>
          <%= render :partial => "create_page", :locals => { :f => f } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $('#new_page').formValidation({
      framework: 'bootstrap',
      icon: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
      },
      fields: {
        'page[name]': {
          validators: {
            notEmpty: {
              message: 'The page name is required'
            },
            remote: {
              message: 'This page name is already exist',
              url: '/pages/page_exist',
              type: 'POST'
            }
          }
        }
      }
    })
  });
</script>

app/views/pages/show.html.erb
<div class="pad-block gray-bg first-pad page-list">
	<div class="container">
    	<div class="main-title filter">
        	<h2>Send files to <%= @user.email %></h2>
					<%= link_to edit_page_path(:id => @page.id), class: "setting-btn" do %>
            <div>
                <button type="button" class="violat-btn"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Setting</button>
            </div>
						<% end%>
        </div>
    	<div class="upload-wrap">
            <div id="dropzone">
								<%= form_tag(upload_pages_path, :method => "post", :multipart => true, :id => "uploadfile",class: "dropzone needsclick") do |f| %>
                <!-- <form action="/upload" class="dropzone needsclick" id="demo-upload"> -->
                    <div class="dz-message needsclick">
                    	<span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span><br />
											<%#= file_field_tag :file %>
											<%= hidden_field_tag :id,params[:id] %>
                        Drop files here or click to upload.<br />
                        <span class="note needsclick">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span>
                    </div>
										<% end%>
                <!-- </form> -->
            </div>
        </div>
				<% if user_signed_in? %>
        <div class="page-title filter">
            <h2>Dropbox Page</h2>

            <div class="btn-group" role="group" aria-label="...">
                <button type="button" class="btn btn-default toggle-view active" data-id="lib-grid"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span></button>
                <button type="button" class="btn btn-default toggle-view" data-id="lib-listing"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span></button>
            </div>
        </div>
        <ul class="page-views lib-grid">
					<% @paths.each do |path| %>
            <li class="page-grid">
                <div class="lib-box">
                    <a href="pages-inner.html" class="lib-icn"><img src="../assets/file.png" alt="" /><div class="status">34 min ago</div></a>
                    <div class="lib-act">
                        <h3><a href="pages-inner.html"><%= path.tr('/', '') %></a></h3>
                        <div><%= link_to dropbox_download_path(path: path), class: "btn download-btn" do %>
													<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
													<% end%>
												</div>
                    </div>
                </div>
            </li>
						<% end %>
            <!-- <li class="page-grid">
                <div class="lib-box">
                    <a href="pages-inner.html" class="lib-icn"><img src="../assets/file.png" alt="" /><div class="status">34 min ago</div></a>
                    <div class="lib-act">
                        <h3><a href="pages-inner.html">My Personal</a></h3>
                        <div class="download-btn"><a href="#"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span></a></div>
                    </div>
                </div>
            </li> -->
        </ul>
  	</div>
	</div>
<% end %>
<script>
	$('#file').change(function() {
	  document.forms["uploadfile"].submit();
	});
// $('#file').click(function(){
//     // alert("test");
//      $.ajax({
// 			 alert()
//            type: "POST",
//            url: '<%= upload_pages_path %>',
//            data: {status: $(this).val(), id: id }
//         });
//  });


$(window).scroll(function() {
	if ($(this).scrollTop() > 1){
		$('header').addClass("sticky");
		$('body').addClass("sticky-b");
	}
	else{
		$('header').removeClass("sticky");
		$('body').removeClass("sticky-b");
	}
});
$('.toggle-view').click(function () {
        $('.toggle-view').removeClass('active');
        $(this).addClass('active');
        var add_class = $(this).attr('data-id');
        if (add_class == 'lib-grid') {
            $('.page-views').removeClass('lib-listing');
            $('.page-views').addClass(add_class);
        } else {
            $('.page-views').removeClass('lib-grid');
            $('.page-views').addClass(add_class);
        }
    });

</script>
<script>

// Dropzone.options.myDropzone({
//   init: function() {
//     this.on("error", function(file, message) { alert(message); });
//   }
// });
// // or if you need to access a Dropzone somewhere else:
// var myDropzone = Dropzone.forElement("div#my-dropzone");
// myDropzone.on("error", function(file, message) { alert(message); });

</script>

app/views/pages/show_page.html.erb
<div class="pad-block gray-bg first-pad page-list">
	<div class="container">
		<div class="main-title filter">
			<h2>Send files to
				<%= @user.email %></h2>
			<% if user_signed_in? && current_user.id == @page.user.id %>
				<%= link_to edit_page_path(:id => @page.id), class: "setting-btn", method: :get do %>
					<div>
						<button type="button" class="violat-btn">
							<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
							Setting</button>
					</div>
				<% end%>
			<% end%>
		</div>
		<% if @dropzone == false %>
			<h4 class="alert alert-danger">sorry your cloud transfer limit has exceeded</h1>
		<% end %>
		<div class="upload-wrap">
			<div id="dropzone" >
				<%= form_tag(upload_pages_path, :method => "post", :multipart => true, :id => "uploadfile",class: "dropzone needsclick ") do |f| %>
				<div class="dz-message needsclick">
					<span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span><br/>
					<%#= file_field_tag :file %>
					<%= hidden_field_tag :id,params[:id] %>
					<%= hidden_field_tag :type,@page.cloud_storage_type %>
					Drop files here or click to upload.<br/>
				</div>
				<% end%>
			</div>
		</div>
		<button type="button" class="hide" id="openModal" data-toggle="modal" data-target="#myModal" data-backdrop="static" data-keyboard="false">Open Modal</button>

		<!-- Modal -->
		<%= render partial: "ques_ans_modal", locals: {ques: @page.page_questions} %>

		<% if user_signed_in? %>
		<div class="page-title filter">
			<h2><%= @page.cloud_storage_type.capitalize %>
				Page</h2>
			<div class="btn-group" role="group" aria-label="...">
				<button type="button" class="btn btn-default toggle-view active" data-id="lib-grid">
					<span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-default toggle-view" data-id="lib-listing">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
				</button>
			</div>
		</div>
		<ul class="page-views lib-grid">
			<% @paths.each do |path| %>
			<li class="page-grid">
				<div class="lib-box">
					<div class="lib-icn">
						<%= image_tag "file.png"%>
						<div class="status"><%= path.created_at.in_time_zone("Chennai").strftime("%m/%d/%Y %H:%M") %></div>
						<% if @page.cloud_storage_type == 'dropbox' %>
							<%= link_to remove_from_dropbox_path(path.page.name, path: path.id), method: :delete,data: { confirm: "Are you sure you want to delete this file?" }, class: "btn remove-file-btn" do %>
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
							<% end%>
						<% elsif @page.cloud_storage_type == 'onedrive' %>
							<%= link_to remove_from_onedrive_path(path.page.name, path: path.id), method: :delete,data: { confirm: "Are you sure you want to delete this file?" }, class: "btn remove-file-btn" do %>
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
							<% end%>
						<% elsif @page.cloud_storage_type == 'googledrive' %>
							<%= link_to remove_from_googledrive_path(path.page.name, path: path.id), method: :delete,data: { confirm: "Are you sure you want to delete this file?" }, class: "btn remove-file-btn" do %>
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
							<% end%>
						<% end%>
					</div>
					<div class="lib-act">
						<h3>
							<% if @page.cloud_storage_type == 'dropbox' && path.uploaded_filename.blank? %>
								<a href="#"><%= path.path.tr('/', '') %></a>
							<% elsif path.uploaded_filename.present? %>
								<a href="#"><%= path.uploaded_filename %></a>
							<% else %>
								<a href="#"><%= path.path %></a>
							<% end %>
						</h3>
						<div>
							<% if @page.cloud_storage_type == 'dropbox' %>
								<%= link_to dropbox_download_path(path.page.name, path: path.id), class: "btn download-btn" do %>
									<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
								<% end%>
							<% elsif @page.cloud_storage_type == 'googledrive' %>
								<%= link_to googledrive_download_path(path.page.name, path: path.id), class: "btn download-btn" do %>
									<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
								<% end%>
							<% elsif @page.cloud_storage_type == 'onedrive' %>
								<%= link_to onedrive_download_path(path.page.name, path: path.id), class: "btn download-btn" do %>
									<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
								<% end%>
							<% end %>
						</div>
					</div>
				</div>
			</li>
			<% end %>
		</ul>
		<% end %>
	</div>
</div>

<% if !user_signed_in? && !cookies["#{@page.name}"].present? %>
<script>
	$(document).ready(function () {
		$("#openModal").click();
	});
</script>
<% end %>

<script>

	$('#file').change(function () {
		document.forms["uploadfile"].submit();
	});

	$(window).scroll(function () {
		if ($(this).scrollTop() > 1) {
			$('header').addClass("sticky");
			$('body').addClass("sticky-b");
		} else {
			$('header').removeClass("sticky");
			$('body').removeClass("sticky-b");
		}
	});
	$('.toggle-view').click(function () {
		$('.toggle-view').removeClass('active');
		$(this).addClass('active');
		var add_class = $(this).attr('data-id');
		if (add_class == 'lib-grid') {
			$('.page-views').removeClass('lib-listing');
			$('.page-views').addClass(add_class);
		} else {
			$('.page-views').removeClass('lib-grid');
			$('.page-views').addClass(add_class);
		}
	});
</script>
<script>
Dropzone.options.uploadfile = {
	maxFilesize: <%= @check_mb %>,

	accept: function(file, done) {

		current_size = <%= @current_size %>
		limit = <%= @limit %>
		kilobytes = (file.size / 1024);
		megabytes = (kilobytes / 1024);
		file_of_size = Number((megabytes).toFixed(2)) ;
		file_of_size = file_of_size + current_size ;
		if(file_of_size > limit.toFixed(2) )
		{
			this.defaultOptions.error(file, 'Sorry your cloud transfer limit has exceeded');
			return false
		}

		if (file.size >= <%= @mb %> )
		{
			return done(this.options.dictFileTooBig.replace("{{filesize}}", Math.round(file.size / 1024 / 10.24) / 100).replace("{{maxFilesize}}", this.options.maxFilesize));
		}
		else
		{
			return done();
		}
	},
}

</script>
<script>
// This example uses jQuery so it creates the Dropzone, only when the DOM has
// loaded.

// Disabling autoDiscover, otherwise Dropzone will try to attach twice.
Dropzone.autoDiscover = false;
$(function() {
	limit = <%= @limit %>
  var myDropzone = new Dropzone(".dropzone");
	<% if @dropzone == false %>
		$('.dropzone').click(function(){
			alert("You don't have enough space to upload this file");
		})
		myDropzone.disable();
	<% end %>
	myDropzone.on("sending", function(file, xhr, formData)
	{
  // Will send the filesize along with the file as POST data.
  	formData.append("filesize", file.size);
		formData.append("limit", limit);
	});
})

</script>