config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'pages', to: "pages#index", as: :pages
    get 'documents/:id', to: "documents#index", as: :documents
    get 'users/:id', to: "users#show", as: :show_user
    get 'users/:id/edit', to: "users#edit", as: :edit_user
    put 'users/:id/update', to: "users#update", as: :update_user
    delete 'user/:id', to: "users#destroy", as: :user_delete
    delete 'page/:id', to: "pages#destroy", as: :page_delete
    get 'decline_request', to: "users#decline_request", as: :decline_request
    put 'decline_request/:id', to: "users#update_request_status", as: :update_request_status
    delete 'decline_request/:id', to: "users#destroy_request", as: :decline_request_delete
  end

  authenticated :admin do
    root :to => "admins/users#index"
  end

  authenticated :user do
    root :to => "dashboard#index"
  end

  devise_for :admins, controllers: { registrations: "admins/registrations",sessions: "admins/sessions", confirmations: "admins/confirmations", passwords: "admins/passwords", unlocks: "admins/unlocks" }
  get 'subscription',to: 'subscriptions#idnex'
  post 'subscriptions', to: 'subscriptions#create'
  get 'authenticates/index'

  devise_for :users, controllers: { registrations: "registrations" }
  post 'check_email', to: 'users#check_email'
  post 'check_page', to: 'users#check_page'
  post 'is_email_exist', to: 'users#is_email_exist'
  get 'staticpage/index'
  get 'staticpage/test'

  get 'staticpage/dropbox'
  get 'staticpage/googledrive'
  get 'staticpage/onedrive'
  get 'staticpage/googleapidrive'

  root to: "dashboard#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/:id/edit', to: 'users#edit', as: :edit_user
  put 'users/:id', to: 'users#update', as: :update_user
  get 'dashboard/privacy_policy', to: 'dashboard#privacy_policy', as: :privacy_policy
  get 'dashboard/switch_plan', to: 'dashboard#switch_plan', as: :switch_plan
  get 'dashboard/addcard/:plan_id', to: 'dashboard#addcard', as: :addcard
  post 'subscription_checkout', to: 'dashboard#subscription_checkout', as: :subscription_checkout
  post 'payment_decline_request', to: 'dashboard#payment_decline_request', as: :payment_decline_request

  resources :pages do
  	collection do
  		post 'upload'
      get ':type', to: 'pages#new_page',as: :new_page
      post 'page_exist', to: 'pages#page_exist', as: :page_exist
      put 'pages/:id', to: 'pages#update'
  	end
  end
  post 'add_question_setting/:id', to: 'pages#add_question', as: :add_question
  get 'remove_question/:id', to: 'pages#remove_question', as: :remove_question
  post 'add_question_answer', to: 'pages#add_question_answer', as: :add_question_answer
  get ':id', to: 'pages#show_page',as: :show_page
  get ':id/dropbox_download' => 'pages#dropbox_download', as: 'dropbox_download'
  delete ':id/remove_from_dropbox' => 'pages#remove_from_dropbox', as: :remove_from_dropbox
  get ':id/googledrive_download', to: 'pages#googledrive_download', as: :googledrive_download
  delete ':id/remove_from_googledrive' => 'pages#remove_from_googledrive', as: :remove_from_googledrive
  get ':id/onedrive_download', to: 'pages#onedrive_download', as: :onedrive_download
  delete ':id/remove_from_onedrive' => 'pages#remove_from_onedrive', as: :remove_from_onedrive


  match "*path" => redirect("/") , via: [:get, :post]
end

app/views/layouts/_admins_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="../../index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>C</b>TR</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>CloudTransfr</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "admin", class: "user-image", alt: "User Image" %>
            <span class="hidden-xs">CloudTransfr Admin</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag "admin", class: "img-circle", alt: "User Image" %>
              <p>
                CloudTransfr Admin
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to "Profile", edit_admin_registration_path, class: "btn btn-default btn-flat" %>
              </div>
              <div class="pull-right">
                <%= link_to "Sign out", destroy_admin_session_path, :method => :delete, class: "btn btn-default btn-flat" %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admins_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <%= image_tag "admin", class: "img-circle", alt: "User Image" %>
        </div>
        <div class="pull-left info">
          <p>CloudTransfr Admin</p>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="<%= (params[:controller] == 'admins/users' && (params[:action] == 'index' || params[:action] == 'show')) ? 'active' : '' %>">
          <%= link_to(root_path) do  %>
            <i class="fa fa-user"></i> <span>Users</span>
          <% end %>
        </li>
        <li class="<%= (params[:controller] == 'admins/pages' || params[:controller] == 'admins/documents') ? 'active' : '' %>">
          <%= link_to(admins_pages_path) do  %>
            <i class="fa fa-folder"></i> <span>Pages</span>
          <% end %>
        </li>
        <li class="<%= (params[:controller] == 'admins/users' && params[:action] == 'decline_request') ? 'active' : '' %>">
          <%= link_to(admins_decline_request_path) do  %>
            <i class="fa fa-check"></i> <span>Declice requests</span>
          <% end %>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<!--<div class="news-letter">
        	<div class="main-title"><h2>Subscribe to our Newsletter</h2></div>
            <form>
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="violat-btn" type="button">Subscribe</button>
              </span>
            </div>
            </form>
        </div>-->
		<div class="foot-cont">
			<div class="foot-logo">
				<a href="#"><%= image_tag("logo.png" )   %></a>
			</div>
		</div>
		<div class="copy">
			<ul>
				<li>Copyright © cloudtransfr 2017</li>
				<li><%= link_to 'Privacy' , privacy_policy_path %></li>
				<li>
					<a href="#">Terms</a>
				</li>
				<li>
					<a href="#">Security</a>
				</li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if user_signed_in? && !current_user.dropbox_detail.present? && !current_user.google_detail.present? && !current_user.onedrive_detail.present? %>
          <%= link_to staticpage_index_path,class:'navbar-brand' do %>
            <%= image_tag("logo.png") %>
          <% end %>
        <% else %>
          <%= link_to root_path,class:'navbar-brand' do %>
            <%= image_tag("logo.png") %>
          <% end %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.dropbox_detail.present? || current_user.google_detail.present? || current_user.onedrive_detail.present? %>
            <li><%= link_to "Pages", pages_path, :class => "#{'active' if params[:controller] == 'pages'}" %></li>
            <% end %>
            <li><%= link_to "Authenticate", staticpage_index_path, :class => "#{'active' if params[:controller] == 'staticpage'}" %></li>

            <li class="dropdown user-drop">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Account" , edit_user_registration_path %></li>
                <li><%= link_to "Switch Plan" , switch_plan_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Try free for 7 days",new_user_registration_path %>
            </li>
            <li class="btn-view">
              <%= link_to "Sign in",user_session_path %>
            </li>
          </ul>
        </div>
      <!-- /.navbar-collapse -->
      <% end %>
    </div>
    <!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title>Cloud Transfr | Admin </title>
    <%= favicon_link_tag 'favicon.png' , type: 'image/png' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admins', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render partial: "layouts/admins_header" %>
      <%= render partial: "layouts/admins_sidebar" %>
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!--  flash error or notice alert -->
        <div class="row">
          <div class="col-xs-12">
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key == 'error' ? 'danger' : 'success' %> alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= value %>
              </div>
            <% end %>
          </div>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/admins_signup.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Cloud Transfr | Admin</title>
  <%= favicon_link_tag 'favicon.png' , type: 'image/png' %>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="/assets/admins/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/assets/admins/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/assets/admins/blue.css">

  <!-- jQuery 2.2.3 -->
  <script src="/assets/admins/jquery-2.2.3.min.js"></script>
  <!-- Bootstrap 3.3.6 -->
  <script src="/assets/admins/bootstrap.min.js"></script>
  <!-- iCheck -->
  <script src="/assets/admins/icheck.min.js"></script>

</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <%= link_to root_path, method: :get do %>
      <b>Admin</b>CloudTransfr
    <% end %>
  </div>
  <%= yield %>

</div>
<!-- /.register-box -->

<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title>Cloud Transfr | Home</title>
    <%= favicon_link_tag 'favicon.png' , type: 'image/png' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- use for payments form  -->
    <script src="https://js.stripe.com/v2/"></script>
    <script src="//oss.maxcdn.com/bootbox/4.2.0/bootbox.min.js"></script>
  </head>

  <body>

    <% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
    </script>
    <% end %>

    <%= render partial: "layouts/header"%>
    <%= yield %>
    <%= render partial: "layouts/footer"%>
  </body>
</html>